=== BeanFactoryPostProcessor

==== 类图

[plantuml,spring-framework-beans-beanfactorypostprocessor.png]
--
@startuml
interface BeanFactoryPostProcessor {
    void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory);
}
interface BeanDefinitionRegistryPostProcessor {
    postProcessBeanDefinitionRegistry(BeanDefinitionRegistry registry);
}

BeanFactoryPostProcessor <|-- BeanDefinitionRegistryPostProcessor
@enduml
--

==== 执行顺序

. 方法执行顺序
.. BeanDefinitionRegistryPostProcessor#postProcessBeanDefinitionRegistry
.. BeanFactoryPostProcessor#postProcessBeanFactory
. 同一方法执行顺序
.. 上下文内置Processor(即AbstractApplicationContext.beanFactoryPostProcessors)
.. 实现PriorityOrdered接口的Processor
.. 实现Ordered接口的Processor
.. 普通的Processor
.. 注意：通过BeanFactoryPostProcessor的回调方法注册的BeanFactoryPostProcessor，时序可能不符合预期.
... 参考代码：PostProcessorRegistrationDelegate#invokeBeanFactoryPostProcessors

=== BeanPostProcessor

==== 类图

[plantuml,spring-framework-beans-beanpostprocessor.png]
--
@startuml
interface BeanPostProcessor {
    default Object postProcessBeforeInitialization(Object bean, String beanName);
    Object postProcessAfterInitialization(Object bean, String beanName);
}
interface MergedBeanDefinitionPostProcessor {
    void postProcessMergedBeanDefinition(RootBeanDefinition beanDefinition, Class<?> beanType, String beanName);
    default void resetBeanDefinition(String beanName);
}
@enduml
--